use crate::{Deployment, ModulePlan};

pub(crate) fn render_generated_source(modules: &[ModulePlan]) -> String {
    let mut source = String::from("// Generated by pixa_runtime/build.rs.\n");
    render_entrypoint_declarations(&mut source, modules);
    source.push_str("const GENERATED_PLUGIN_MODULES: &[GeneratedPluginModule] = &[\n");
    let mut entrypoint_index = 0_usize;
    for module in modules {
        let entrypoint = if module.deployment == Deployment::HostLinkedPlugin {
            let expression = format!("Some(pixa_generated_plugin_entry_{entrypoint_index})");
            entrypoint_index += 1;
            expression
        } else {
            "None".to_string()
        };
        source.push_str("    GeneratedPluginModule {\n");
        source.push_str(&format!(
            "        module_id: {},\n",
            rust_string(&module.module_id)
        ));
        source.push_str(&format!("        abi_version: {},\n", module.abi_version));
        source.push_str(&format!(
            "        deployment: GeneratedPluginDeployment::{},\n",
            module.deployment.rust_variant()
        ));
        source.push_str(&format!(
            "        package_name: {},\n",
            rust_option_string(&module.package_name)
        ));
        source.push_str(&format!(
            "        implementation_language: {},\n",
            rust_option_string(&module.implementation_language)
        ));
        source.push_str(&format!(
            "        entrypoint_symbol: {},\n",
            rust_option_string(&module.entrypoint_symbol)
        ));
        source.push_str(&format!("        entrypoint: {entrypoint},\n"));
        source.push_str("        capabilities: GeneratedPluginCapabilities {\n");
        source.push_str(&format!(
            "            fetcher: {}, decoder: {}, processor: {}, cache_store: {},\n",
            module.capabilities.fetcher,
            module.capabilities.decoder,
            module.capabilities.processor,
            module.capabilities.cache_store
        ));
        source.push_str(&format!(
            "            host_managed_runtime: {}, binary_messages: {}, owned_buffers: {}, stream_handles: {},\n",
            module.capabilities.host_managed_runtime,
            module.capabilities.binary_messages,
            module.capabilities.owned_buffers,
            module.capabilities.stream_handles
        ));
        source.push_str("        },\n");
        source.push_str("        routes: GeneratedPluginRoutes {\n");
        source.push_str(&format!(
            "            fetcher_source_kinds: {},\n",
            render_str_slice(&module.routes.fetcher_source_kinds)
        ));
        source.push_str(&format!(
            "            video_frame_output_mime_types: {},\n",
            render_str_slice(&module.routes.video_frame_output_mime_types)
        ));
        source.push_str(&format!(
            "            decoder_format_ids: {},\n",
            render_str_slice(&module.routes.decoder_format_ids)
        ));
        source.push_str(&format!(
            "            decoder_mime_types: {},\n",
            render_str_slice(&module.routes.decoder_mime_types)
        ));
        source.push_str(&format!(
            "            decoder_signatures: {},\n",
            render_decoder_signatures(&module.routes.decoder_signatures)
        ));
        source.push_str(&format!(
            "            processor_operations: {},\n",
            render_str_slice(&module.routes.processor_operations)
        ));
        source.push_str(&format!(
            "            cache_store_namespaces: {},\n",
            render_str_slice(&module.routes.cache_store_namespaces)
        ));
        source.push_str("        },\n");
        source.push_str("    },\n");
    }
    source.push_str("];\n");
    source
}

fn render_entrypoint_declarations(source: &mut String, modules: &[ModulePlan]) {
    let host_linked: Vec<&ModulePlan> = modules
        .iter()
        .filter(|module| module.deployment == Deployment::HostLinkedPlugin)
        .collect();
    if host_linked.is_empty() {
        return;
    }
    source.push_str("unsafe extern \"C\" {\n");
    for (index, module) in host_linked.iter().enumerate() {
        let symbol = module.entrypoint_symbol.as_deref().unwrap_or_default();
        source.push_str(&format!("    #[link_name = {}]\n", rust_string(symbol)));
        source.push_str(&format!(
            "    fn pixa_generated_plugin_entry_{index}(host: *const PixaPluginHostApiV1, module: *mut PixaPluginModuleApiV1) -> i32;\n"
        ));
    }
    source.push_str("}\n");
}

fn rust_option_string(value: &Option<String>) -> String {
    value
        .as_ref()
        .map(|value| format!("Some({})", rust_string(value)))
        .unwrap_or_else(|| "None".to_string())
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn render_str_slice(values: &[String]) -> String {
    let values = values
        .iter()
        .map(|value| rust_string(value))
        .collect::<Vec<String>>()
        .join(", ");
    format!("&[{values}]")
}

fn render_decoder_signatures(signatures: &[crate::DecoderSignaturePlan]) -> String {
    let values = signatures
        .iter()
        .map(|signature| {
            let magic = signature
                .magic
                .iter()
                .map(|byte| format!("0x{byte:02x}"))
                .collect::<Vec<String>>()
                .join(", ");
            format!(
                "GeneratedPluginDecoderSignature {{ offset: {}, magic: &[{}], mime_type: {}, format_id: {} }}",
                signature.offset,
                magic,
                rust_string(&signature.mime_type),
                rust_option_string(&signature.format_id),
            )
        })
        .collect::<Vec<String>>()
        .join(", ");
    format!("&[{values}]")
}
